{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shiny.semantic
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shiny.semantic_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shiny.semantic/shiny.semantic_{{ version }}.tar.gz
  sha256: c5107eca2b1031b4c8a42a5fd3eb8694b58b8debd898c9cb4feaae27870557a1

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-glue
    - r-htmltools >=0.2.6
    - r-htmlwidgets >=0.8
    - r-jsonlite
    - r-magrittr
    - r-purrr >=0.2.2
    - r-semantic.assets >=1.1.0
    - r-shiny >=0.12.1
  run:
    - r-base
    - r-r6
    - r-glue
    - r-htmltools >=0.2.6
    - r-htmlwidgets >=0.8
    - r-jsonlite
    - r-magrittr
    - r-purrr >=0.2.2
    - r-semantic.assets >=1.1.0
    - r-shiny >=0.12.1

test:
  commands:
    - $R -e "library('shiny.semantic')"           # [not win]
    - "\"%R%\" -e \"library('shiny.semantic')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shiny.semantic
  license: MIT
  summary: Creating a great user interface for your Shiny apps can be a hassle, especially if you want to work purely in R and don't want to use, for instance HTML templates. This package adds support for a powerful UI library Semantic UI - <http://semantic-ui.com/>. It also supports universal UI input binding that works
    with various DOM elements.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shiny.semantic
# Type: Package
# Title: Semantic UI Support for Shiny
# Version: 0.3.0
# Authors@R: c(person("Filip", "Stachura", email = "filip@appsilon.com", role = "aut"), person("Krystian", "Igras", email = "krystian@appsilon.com", role = "aut"), person("Adam", "Forys", email = "adam@appsilon.com", role = "aut"), person("Dominik", "Krzeminski", email = "dominik@appsilon.com", role = "cre"), person(family = "Appsilon Sp. z o.o.", role = c("cph")))
# Description: Creating a great user interface for your Shiny apps can be a hassle, especially if you want to work purely in R and don't want to use, for instance HTML templates. This package adds support for a powerful UI library Semantic UI - <http://semantic-ui.com/>. It also supports universal UI input binding that works with various DOM elements.
# BugReports: https://github.com/Appsilon/shiny.semantic/issues
# Encoding: UTF-8
# LazyData: TRUE
# License: MIT + file LICENSE
# Imports: shiny (>= 0.12.1), htmltools (>= 0.2.6), htmlwidgets (>= 0.8), purrr (>= 0.2.2), magrittr, jsonlite
# Suggests: dplyr, gapminder, testthat, lintr, covr
# RoxygenNote: 7.0.2.9000
# NeedsCompilation: no
# Packaged: 2020-03-12 12:25:59 UTC; dominik
# Author: Filip Stachura [aut], Krystian Igras [aut], Adam Forys [aut], Dominik Krzeminski [cre], Appsilon Sp. z o.o. [cph]
# Maintainer: Dominik Krzeminski <dominik@appsilon.com>
# Repository: CRAN
# Date/Publication: 2020-03-13 07:10:02 UTC
