{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shiny.semantic
  version: {{ version|replace("-", "_") }}

source:
  fn: shiny.semantic_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shiny.semantic_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shiny.semantic/shiny.semantic_{{ version }}.tar.gz
  sha256: 25bc6dd726e47f01c612c3dc70e83519324e9913130ef2c659885299019d9c4d

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-htmltools >=0.2.6
    - r-htmlwidgets >=0.8
    - r-jsonlite
    - r-magrittr
    - r-purrr >=0.2.2
    - r-shiny >=0.12.1
  run:
    - r-base
    - r-htmltools >=0.2.6
    - r-htmlwidgets >=0.8
    - r-jsonlite
    - r-magrittr
    - r-purrr >=0.2.2
    - r-shiny >=0.12.1

test:
  commands:
    - $R -e "library('shiny.semantic')"           # [not win]
    - "\"%R%\" -e \"library('shiny.semantic')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shiny.semantic
  license: MIT
  license_file: LICENSE
  summary: Creating a great user interface for your Shiny apps can be a hassle, especially if you want to work purely in R and don't want to use, for instance HTML
    templates. This package adds support for a powerful UI library Semantic UI - <http://semantic-ui.com/>. It also supports universal UI input  binding that works
    with various DOM elements.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
