appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: WvcLcjxEWJF9LHlRkxglxQS8T+lOHMqpBMm/pzejBjlY25OYmxsQtzkxE9qh1CaQLMHnbrQ9S7ke+zEmoYxUtPAIGhqZmUkGStKpbCCKnp5qmyRcfHEm0o57hnV47CKY0Hq6zdx94aLLCIaBz+tqpxJSmg/4cWJ9tMk1Y+U8VDzEZ5ap6g2UasTVykmMMkGYz9wjAH/FdqvGSwUHTgMj1GiHqa43Uwos6wGLF1swDLBrYhSWZppAlXUeXlNwNQ1sgp8GjaK23eJQIEram+XDSct0HKMkLj+B9o5TPUrKu2aRwpAf8G+kxl7otRogu0M4VNV5IkN3K1xkAug/KiMs2tSXDM1fMuyITtKVPv6ynXLQuLgUt6uCRG1kiUOX8LFB9GJ8OW2JwbHuTGgpgowaOlto6R1MM0S492GXqUJ5P0++Pmqzadw0biNRPJGH9CGPnqtnT+/vuIrzlmFBo+v3oCbpcaAj3Z+4bgsiOQA9fHJvgmMMtKuMUaXZFDzaFBAKYpw742KC1C82oKLuh4SxCNTOaOJTIaMZCmj+ASa6FatWvepBm3tR+9AVviokbyuxvj8xMrpUR+0wpIAE0YrH6YkMud881MOr4dOQ/Hdyf+Ti6yeI8+dU45YWTB464ndt5Dv9m/BeQ7kvoiKdTpkUSALWkgeTKs0ETPm64V3whAU=
conda_forge_output_validation: true
