travis:
  secure:
    BINSTAR_TOKEN: VtxRJd5JvTikViIf2qWLtowZCEGxYJT4HF1eMpakNIjHc/ygie1tzLuQM9SrUZAK0ZkhwGKiH7zMrko/xrVhQj3mTrLobqrDTy5wmuKflodhz2h8Qx+cXSC5eRIqeUt0rBoDld2AzG9pLzWabHshcijNmtg4cWFodvTsBHxYmxTTDNJ2GSv22hm/iDqB/Ca/BKoanHDTmOTpj96H34vHI350wtUBkGp2o99RigOpSNLfEeaqy6SSpR15CaEi9Iu8+/VcnhzQlkr5njMRrYt2AB6jq+pknxTUJ4e6nDWoRuzZ4P05at5AHlNXoq3D5JL9e+93MywPgTGUWhSp6qIS95fv3T2kT4XYzlsdxxyEWcC4vlrk8R3FRalVP0XxjlgnYINsngK24aoaBzbB8Y/r1bQAz0jEcbQSEX1rzTb6Ru8CuTO8Lv0A9GEs1E5JeSggwvMiHTJluYebruFSIXB5l220MRaimeNFeZz97qsYcG+Co5YGKiWSWNvZCvyYeSqYdYZPpqqMaXKCWR1eymRPN+i96SlC2dJy9RDnHB/hEF+Cq7nUrxsjC5XP41SpNs/ZB0IBPv9te/sOWkNY8Ou0ReEiovgSSaV2OIsquOAmZB16Gl5pgPKDjJU/gF4COscHn4craNUNOMhpOXQMpTsbNMnL+CNWJdeON470ldT6d+o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
